<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6.2 Regresión lineal simple | Estadística para Contadores y Auditores con R</title>
  <meta name="description" content="Libro de Estadística para Contadores y Auditores con R" />
  <meta name="generator" content="bookdown 0.12 and GitBook 2.6.7" />

  <meta property="og:title" content="6.2 Regresión lineal simple | Estadística para Contadores y Auditores con R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="images/cover.png" />
  <meta property="og:description" content="Libro de Estadística para Contadores y Auditores con R" />
  <meta name="github-repo" content="oswnavarre/" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6.2 Regresión lineal simple | Estadística para Contadores y Auditores con R" />
  
  <meta name="twitter:description" content="Libro de Estadística para Contadores y Auditores con R" />
  <meta name="twitter:image" content="images/cover.png" />

<meta name="author" content="Oswaldo Navarrete Carreño" />
<meta name="author" content="María Alexandra Chavez P." />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="correl.html">
<link rel="next" href="mult.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Estadística para Contadores y Auditores Con R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> ¿A quién va dirigido este libro?</a><ul>
<li class="chapter" data-level="1.1" data-path="que-es-r.html"><a href="que-es-r.html"><i class="fa fa-check"></i><b>1.1</b> ¿Qué es R?</a></li>
<li class="chapter" data-level="1.2" data-path="que-es-rstudio.html"><a href="que-es-rstudio.html"><i class="fa fa-check"></i><b>1.2</b> ¿Qué es Rstudio?</a></li>
<li class="chapter" data-level="1.3" data-path="packages.html"><a href="packages.html"><i class="fa fa-check"></i><b>1.3</b> Paquetes</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Estadística. Conceptos Básicos.</a><ul>
<li class="chapter" data-level="2.1" data-path="estypes.html"><a href="estypes.html"><i class="fa fa-check"></i><b>2.1</b> Estadística descriptiva e inferencial</a></li>
<li class="chapter" data-level="2.2" data-path="tipos-de-variables.html"><a href="tipos-de-variables.html"><i class="fa fa-check"></i><b>2.2</b> Tipos de Variables</a><ul>
<li class="chapter" data-level="2.2.1" data-path="tipos-de-variables.html"><a href="tipos-de-variables.html#niveles-de-medicion"><i class="fa fa-check"></i><b>2.2.1</b> Niveles de medición</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="otros-conceptos-importantes.html"><a href="otros-conceptos-importantes.html"><i class="fa fa-check"></i><b>2.3</b> Otros conceptos importantes</a></li>
<li class="chapter" data-level="2.4" data-path="tipos-de-estudio-en-investigacion.html"><a href="tipos-de-estudio-en-investigacion.html"><i class="fa fa-check"></i><b>2.4</b> Tipos de estudio en investigación</a></li>
<li class="chapter" data-level="2.5" data-path="primerR.html"><a href="primerR.html"><i class="fa fa-check"></i><b>2.5</b> Primeros pasos en R</a></li>
<li class="chapter" data-level="2.6" data-path="tendcentr.html"><a href="tendcentr.html"><i class="fa fa-check"></i><b>2.6</b> Medidas de Tendencia Central</a><ul>
<li class="chapter" data-level="2.6.1" data-path="tendcentr.html"><a href="tendcentr.html#media"><i class="fa fa-check"></i><b>2.6.1</b> Media</a></li>
<li class="chapter" data-level="2.6.2" data-path="tendcentr.html"><a href="tendcentr.html#mediana"><i class="fa fa-check"></i><b>2.6.2</b> Mediana</a></li>
<li class="chapter" data-level="2.6.3" data-path="tendcentr.html"><a href="tendcentr.html#moda"><i class="fa fa-check"></i><b>2.6.3</b> Moda</a></li>
<li class="chapter" data-level="2.6.4" data-path="tendcentr.html"><a href="tendcentr.html#cuando-usar-la-media-o-la-mediana"><i class="fa fa-check"></i><b>2.6.4</b> ¿Cuándo usar la media o la mediana?</a></li>
<li class="chapter" data-level="2.6.5" data-path="tendcentr.html"><a href="tendcentr.html#calculo-de-las-medidas-de-tendencia-central-en-r"><i class="fa fa-check"></i><b>2.6.5</b> Cálculo de las medidas de tendencia central en R</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="medidas-de-posicion-cuantiles.html"><a href="medidas-de-posicion-cuantiles.html"><i class="fa fa-check"></i><b>2.7</b> Medidas de posición (Cuantiles)</a><ul>
<li class="chapter" data-level="2.7.1" data-path="medidas-de-posicion-cuantiles.html"><a href="medidas-de-posicion-cuantiles.html#tipos-de-cuantiles"><i class="fa fa-check"></i><b>2.7.1</b> Tipos de Cuantiles</a></li>
<li class="chapter" data-level="2.7.2" data-path="medidas-de-posicion-cuantiles.html"><a href="medidas-de-posicion-cuantiles.html#calculo-de-cuantiles"><i class="fa fa-check"></i><b>2.7.2</b> Cálculo de cuantiles</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="dispersion.html"><a href="dispersion.html"><i class="fa fa-check"></i><b>2.8</b> Medidas de dispersión</a><ul>
<li class="chapter" data-level="2.8.1" data-path="dispersion.html"><a href="dispersion.html#rango"><i class="fa fa-check"></i><b>2.8.1</b> Rango</a></li>
<li class="chapter" data-level="2.8.2" data-path="dispersion.html"><a href="dispersion.html#varianza"><i class="fa fa-check"></i><b>2.8.2</b> Varianza</a></li>
<li class="chapter" data-level="2.8.3" data-path="dispersion.html"><a href="dispersion.html#desviacion"><i class="fa fa-check"></i><b>2.8.3</b> Desviación</a></li>
<li class="chapter" data-level="2.8.4" data-path="dispersion.html"><a href="dispersion.html#medidas-de-dispersion-en-r"><i class="fa fa-check"></i><b>2.8.4</b> Medidas de dispersión en R</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="tablas-de-frecuencia.html"><a href="tablas-de-frecuencia.html"><i class="fa fa-check"></i><b>2.9</b> Tablas de frecuencia</a><ul>
<li class="chapter" data-level="2.9.1" data-path="tablas-de-frecuencia.html"><a href="tablas-de-frecuencia.html#variables-cualitativas"><i class="fa fa-check"></i><b>2.9.1</b> Variables Cualitativas</a></li>
<li class="chapter" data-level="2.9.2" data-path="tablas-de-frecuencia.html"><a href="tablas-de-frecuencia.html#variables-cuantitativas"><i class="fa fa-check"></i><b>2.9.2</b> Variables Cuantitativas</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="tablas-de-contingencia.html"><a href="tablas-de-contingencia.html"><i class="fa fa-check"></i><b>2.10</b> Tablas de Contingencia</a><ul>
<li class="chapter" data-level="2.10.1" data-path="tablas-de-contingencia.html"><a href="tablas-de-contingencia.html#las-funciones-spread-y-gather"><i class="fa fa-check"></i><b>2.10.1</b> Las funciones <code>spread</code> y <code>gather</code></a></li>
</ul></li>
<li class="chapter" data-level="2.11" data-path="graficos-y-visualizacion.html"><a href="graficos-y-visualizacion.html"><i class="fa fa-check"></i><b>2.11</b> Gráficos y Visualización</a><ul>
<li class="chapter" data-level="2.11.1" data-path="graficos-y-visualizacion.html"><a href="graficos-y-visualizacion.html#histogramas"><i class="fa fa-check"></i><b>2.11.1</b> Histogramas</a></li>
<li class="chapter" data-level="2.11.2" data-path="graficos-y-visualizacion.html"><a href="graficos-y-visualizacion.html#diagrama-de-barras"><i class="fa fa-check"></i><b>2.11.2</b> Diagrama de barras</a></li>
<li class="chapter" data-level="2.11.3" data-path="graficos-y-visualizacion.html"><a href="graficos-y-visualizacion.html#boxes"><i class="fa fa-check"></i><b>2.11.3</b> Diagramas de Caja y valores atípicos</a></li>
</ul></li>
<li class="chapter" data-level="2.12" data-path="ejercicios.html"><a href="ejercicios.html"><i class="fa fa-check"></i><b>2.12</b> Ejercicios</a><ul>
<li class="chapter" data-level="2.12.1" data-path="ejercicios.html"><a href="ejercicios.html#teoricos"><i class="fa fa-check"></i><b>2.12.1</b> Teóricos</a></li>
<li class="chapter" data-level="2.12.2" data-path="ejercicios.html"><a href="ejercicios.html#practicos"><i class="fa fa-check"></i><b>2.12.2</b> Prácticos</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="distr.html"><a href="distr.html"><i class="fa fa-check"></i><b>3</b> Distribuciones de probabilidad</a><ul>
<li class="chapter" data-level="3.1" data-path="variable-aleatoria-y-distribucion-de-probabilidad.html"><a href="variable-aleatoria-y-distribucion-de-probabilidad.html"><i class="fa fa-check"></i><b>3.1</b> Variable aleatoria y distribución de probabilidad</a></li>
<li class="chapter" data-level="3.2" data-path="funciones-de-densidad-de-probabilidad.html"><a href="funciones-de-densidad-de-probabilidad.html"><i class="fa fa-check"></i><b>3.2</b> Funciones de Densidad de Probabilidad</a></li>
<li class="chapter" data-level="3.3" data-path="distribucion-de-probabilidad-normal.html"><a href="distribucion-de-probabilidad-normal.html"><i class="fa fa-check"></i><b>3.3</b> Distribución de Probabilidad Normal</a><ul>
<li class="chapter" data-level="3.3.1" data-path="distribucion-de-probabilidad-normal.html"><a href="distribucion-de-probabilidad-normal.html#dne"><i class="fa fa-check"></i><b>3.3.1</b> Distribución Normal Estándar</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="distribucion-t-de-student.html"><a href="distribucion-t-de-student.html"><i class="fa fa-check"></i><b>3.4</b> Distribución <span class="math inline">\(t\)</span> de Student</a></li>
<li class="chapter" data-level="3.5" data-path="distribucion-normal-y-t-de-student-en-r.html"><a href="distribucion-normal-y-t-de-student-en-r.html"><i class="fa fa-check"></i><b>3.5</b> Distribución normal y <span class="math inline">\(t\)</span> de Student en R</a><ul>
<li class="chapter" data-level="3.5.1" data-path="distribucion-normal-y-t-de-student-en-r.html"><a href="distribucion-normal-y-t-de-student-en-r.html#ejemplos"><i class="fa fa-check"></i><b>3.5.1</b> Ejemplos</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="sampl.html"><a href="sampl.html"><i class="fa fa-check"></i><b>4</b> Muestreo</a></li>
<li class="chapter" data-level="5" data-path="icph.html"><a href="icph.html"><i class="fa fa-check"></i><b>5</b> Intervalos de Confianza y Pruebas de Hipótesis</a><ul>
<li class="chapter" data-level="5.1" data-path="ic.html"><a href="ic.html"><i class="fa fa-check"></i><b>5.1</b> Intervalos de Confianza</a><ul>
<li class="chapter" data-level="5.1.1" data-path="ic.html"><a href="ic.html#interpretacion-de-un-intervalo-de-confianza"><i class="fa fa-check"></i><b>5.1.1</b> Interpretación de un intervalo de confianza</a></li>
<li class="chapter" data-level="5.1.2" data-path="ic.html"><a href="ic.html#icmu"><i class="fa fa-check"></i><b>5.1.2</b> Intervalo de Confianza para la media <span class="math inline">\(\mu\)</span></a></li>
<li class="chapter" data-level="5.1.3" data-path="ic.html"><a href="ic.html#intervalo-de-confianza-para-la-proporcion"><i class="fa fa-check"></i><b>5.1.3</b> Intervalo de Confianza para la proporción</a></li>
<li class="chapter" data-level="5.1.4" data-path="ic.html"><a href="ic.html#intervalo-de-confianza-para-la-diferencia-de-medias"><i class="fa fa-check"></i><b>5.1.4</b> Intervalo de Confianza para la diferencia de medias</a></li>
<li class="chapter" data-level="5.1.5" data-path="ic.html"><a href="ic.html#intervalo-de-confianza-para-la-diferencia-de-proporciones"><i class="fa fa-check"></i><b>5.1.5</b> Intervalo de Confianza para la diferencia de proporciones</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="ph.html"><a href="ph.html"><i class="fa fa-check"></i><b>5.2</b> Pruebas de hipótesis</a><ul>
<li class="chapter" data-level="5.2.1" data-path="ph.html"><a href="ph.html#significancia-tamano-del-efecto-y-potencia-de-la-prueba"><i class="fa fa-check"></i><b>5.2.1</b> Significancia, tamaño del efecto y potencia de la prueba</a></li>
<li class="chapter" data-level="5.2.2" data-path="ph.html"><a href="ph.html#pvalor"><i class="fa fa-check"></i><b>5.2.2</b> El valor <span class="math inline">\(p\)</span></a></li>
<li class="chapter" data-level="5.2.3" data-path="ph.html"><a href="ph.html#estadisticos-de-prueba"><i class="fa fa-check"></i><b>5.2.3</b> Estadísticos de Prueba</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="intervalos-de-confianza-en-r.html"><a href="intervalos-de-confianza-en-r.html"><i class="fa fa-check"></i><b>5.3</b> Intervalos de confianza en R</a><ul>
<li class="chapter" data-level="5.3.1" data-path="intervalos-de-confianza-en-r.html"><a href="intervalos-de-confianza-en-r.html#para-la-media"><i class="fa fa-check"></i><b>5.3.1</b> Para la media</a></li>
<li class="chapter" data-level="5.3.2" data-path="intervalos-de-confianza-en-r.html"><a href="intervalos-de-confianza-en-r.html#para-la-proporcion"><i class="fa fa-check"></i><b>5.3.2</b> Para la proporción</a></li>
<li class="chapter" data-level="5.3.3" data-path="intervalos-de-confianza-en-r.html"><a href="intervalos-de-confianza-en-r.html#diferencia-de-medias"><i class="fa fa-check"></i><b>5.3.3</b> Diferencia de medias</a></li>
<li class="chapter" data-level="5.3.4" data-path="intervalos-de-confianza-en-r.html"><a href="intervalos-de-confianza-en-r.html#diferencia-de-proporciones"><i class="fa fa-check"></i><b>5.3.4</b> Diferencia de proporciones</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="pruebas-de-hipotesis-en-r.html"><a href="pruebas-de-hipotesis-en-r.html"><i class="fa fa-check"></i><b>5.4</b> Pruebas de Hipótesis en R</a><ul>
<li class="chapter" data-level="5.4.1" data-path="pruebas-de-hipotesis-en-r.html"><a href="pruebas-de-hipotesis-en-r.html#para-la-media-1"><i class="fa fa-check"></i><b>5.4.1</b> Para la media</a></li>
<li class="chapter" data-level="5.4.2" data-path="pruebas-de-hipotesis-en-r.html"><a href="pruebas-de-hipotesis-en-r.html#para-la-proporcion-1"><i class="fa fa-check"></i><b>5.4.2</b> Para la proporción</a></li>
<li class="chapter" data-level="5.4.3" data-path="pruebas-de-hipotesis-en-r.html"><a href="pruebas-de-hipotesis-en-r.html#para-la-diferencia-de-medias"><i class="fa fa-check"></i><b>5.4.3</b> Para la diferencia de medias</a></li>
<li class="chapter" data-level="5.4.4" data-path="pruebas-de-hipotesis-en-r.html"><a href="pruebas-de-hipotesis-en-r.html#para-la-diferencia-de-proporciones"><i class="fa fa-check"></i><b>5.4.4</b> Para la diferencia de proporciones</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="ejercicios-1.html"><a href="ejercicios-1.html"><i class="fa fa-check"></i><b>5.5</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="methods.html"><a href="methods.html"><i class="fa fa-check"></i><b>6</b> Correlación y Regresión</a><ul>
<li class="chapter" data-level="6.1" data-path="correl.html"><a href="correl.html"><i class="fa fa-check"></i><b>6.1</b> Coeficiente de Correlación</a></li>
<li class="chapter" data-level="6.2" data-path="lineal.html"><a href="lineal.html"><i class="fa fa-check"></i><b>6.2</b> Regresión lineal simple</a><ul>
<li class="chapter" data-level="6.2.1" data-path="lineal.html"><a href="lineal.html#regresion-lineal-en-r"><i class="fa fa-check"></i><b>6.2.1</b> Regresión lineal en R</a></li>
<li class="chapter" data-level="6.2.2" data-path="lineal.html"><a href="lineal.html#coefregre"><i class="fa fa-check"></i><b>6.2.2</b> Interpretación de los coeficientes de regresión</a></li>
<li class="chapter" data-level="6.2.3" data-path="lineal.html"><a href="lineal.html#bondad-de-ajuste-del-modelo-de-regresion"><i class="fa fa-check"></i><b>6.2.3</b> Bondad de Ajuste del modelo de regresión</a></li>
<li class="chapter" data-level="6.2.4" data-path="lineal.html"><a href="lineal.html#pruebas-de-hipotesis-para-los-coeficientes-de-la-regresion"><i class="fa fa-check"></i><b>6.2.4</b> Pruebas de Hipótesis para los coeficientes de la regresión</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="mult.html"><a href="mult.html"><i class="fa fa-check"></i><b>6.3</b> Regresión Múltiple</a></li>
<li class="chapter" data-level="6.4" data-path="regresion-logistica.html"><a href="regresion-logistica.html"><i class="fa fa-check"></i><b>6.4</b> Regresión logística</a><ul>
<li class="chapter" data-level="6.4.1" data-path="regresion-logistica.html"><a href="regresion-logistica.html#modelo-de-regresion-logistica"><i class="fa fa-check"></i><b>6.4.1</b> Modelo de regresión logística</a></li>
<li class="chapter" data-level="6.4.2" data-path="regresion-logistica.html"><a href="regresion-logistica.html#regresion-logistica-en-r"><i class="fa fa-check"></i><b>6.4.2</b> Regresión logística en R</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="ejercicios-2.html"><a href="ejercicios-2.html"><i class="fa fa-check"></i><b>6.5</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="bibliografia.html"><a href="bibliografia.html"><i class="fa fa-check"></i>Bibliografía</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Estadística para Contadores y Auditores con R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="lineal" class="section level2">
<h2><span class="header-section-number">6.2</span> Regresión lineal simple</h2>
<p>Al inicio de este capítulo usamos diagramas de dispersión o gráficos de dispersión para analizar la relación entre dos variables. Luego en la seccion <a href="correl.html#correl">6.1</a> se analizó la relación entre la publicidad y las ventas de 100 empresas utilizando el coeficiente de correlación. La correlación no contesta preguntas como ¿influye la publicidad sobre las ventas? Si la publicidad aumenta ¿cuánto aumentarán las ventas? En esta sección utilizaremos el análisis de regresión para analizar la relación entre la publicidad y las ventas.</p>
<p>El análisis de regresión es una forma más avanzada que la correlación para analizar la relación entre variables. Las principales diferencias entre la correlación y la regresión son:</p>
<ul>
<li>La regresión puede investigar las relaciones entre dos o más variables.</li>
<li>Se estima una relación de causalidad entre la o las variables explicativas y la variable dependiente.</li>
<li>Se mide la influencia de cada variable explicativa sobre la variable dependiente.</li>
<li>Se puede medir la significancia de cada variable explicativa.</li>
</ul>
<p>Se espera que la publicidad explique las ventas. La publicidad es la variable explicativa o independiente y se ubica sobre el eje de las <span class="math inline">\(X\)</span>, y el nivel de ventas es una variable explicada o dependiente y se ubica sobre el eje de las <span class="math inline">\(Y\)</span>. El análisis de regresión describe esta relación causal ajustando una línea recta a los datos como se observa en la figura <a href="lineal.html#fig:regre1">6.8</a>. Esta recta de regresión es creciente, lo que se relaciona con el valor del coeficiente de correlación previamente calculado cuyo signo es positivo, por lo que altos niveles de publicidad se asocian con altos niveles de ventas y viceversa.</p>
<div class="figure" style="text-align: center"><span id="fig:regre1"></span>
<img src="EPCA_files/figure-html/regre1-1.png" alt="Recta de regresión" width="50%" />
<p class="caption">
Figura 6.8: Recta de regresión
</p>
</div>
<p>En los datos cuando la publicidad es <span class="math inline">\(64.76\)</span> las ventas son <span class="math inline">\(250.35\)</span>, pero para la recta de regresión cuando la publicidad es igual a <span class="math inline">\(64.76\)</span> ventas son iguales a 289.29. Este valor es cercano pero no igual al valor real, la diferencia refleja la ausencia de una correlación perfecta entre las dos variables. La diferencia entre el valor real <span class="math inline">\(Y\)</span> y el valor predicho <span class="math inline">\(\hat{Y}\)</span> recibe el nombre de <strong>error</strong> o <strong>residual</strong>, en la figura <a href="lineal.html#fig:error1">6.9</a> se observa el error.</p>
<div class="figure" style="text-align: center"><span id="fig:error1"></span>
<img src="error.png" alt="Error en la estimación" width="60%" />
<p class="caption">
Figura 6.9: Error en la estimación
</p>
</div>
<p>El error puede provenir de diversas fuentes y deberse a varios factores por ejemplo en el contexto que estamos analizando, la diferencia entre las ventas predichas y las ventas reales se puede deber a errores de medición, a condiciones externas a la empresa como la situación política o a condiciones internas como problemas en la producción, etc. Todos los factores están dentro del término de error y esto significa que las observaciones caen alrededor de la recta de regresión y no en ella. Si hay muchos de estos factores, sin uno en particular que predomine y además existe independencia entre los factores se puede asumir que los errores se distribuyen normalmente alrededor de la recta de regresión.</p>
<p><span class="math display" id="eq:regre2">\[\begin{equation}
\hat{Y}_i = \beta_0 + \beta_1 X_i
    \tag{6.4}
\end{equation}\]</span></p>
<p>donde:</p>
<ul>
<li><span class="math inline">\(\hat{Y}_i\)</span> es el valor predicho de <span class="math inline">\(Y\)</span> para la observación <span class="math inline">\(i\)</span></li>
<li><span class="math inline">\(X_i\)</span> es el valor de la variable explicativa para la observación <span class="math inline">\(i\)</span></li>
<li><span class="math inline">\(\beta_0\)</span> y <span class="math inline">\(\beta_1\)</span> son los coeficientes fijos que serán estimados; <span class="math inline">\(\beta_0\)</span> representa el intercepto de la recta de regresión con el eje de las <span class="math inline">\(Y\)</span> y <span class="math inline">\(\beta_1\)</span> mide la pendiente. En la figura <a href="lineal.html#fig:rectareg">6.10</a> se aprecia el intercepto y la pendiente de la recta de regresión lineal.</li>
</ul>
<div class="figure" style="text-align: center"><span id="fig:rectareg"></span>
<img src="regre3.png" alt="Intercepto y pendiente en la recta de regresión" width="50%" />
<p class="caption">
Figura 6.10: Intercepto y pendiente en la recta de regresión
</p>
</div>
<p>Lo primordial del análisis de regresión consiste en determinar los valores de <span class="math inline">\(\beta_0\)</span> y <span class="math inline">\(\beta_1\)</span>. Para esto se parte de que la diferencia entre el valor real y el valor predicho es igual al error o dicho de otra forma el valor real es igual al valor predicho más el error:</p>
<p><span class="math display" id="eq:regre3">\[\begin{equation}
Y_i=\hat{Y}_i+e_i 
    \tag{6.5}
\end{equation}\]</span></p>
<p>Reemplazando la ecuación <a href="lineal.html#eq:regre3">(6.5)</a> en <a href="lineal.html#eq:regre2">(6.4)</a> se obtiene:</p>
<p><span class="math display" id="eq:regre4">\[\begin{equation}
Y_i=\beta_0 + \beta_1 X_i+e_i 
    \tag{6.6}
\end{equation}\]</span></p>
<p>Con la ecuación <a href="lineal.html#eq:regre4">(6.6)</a> se puede entender que las ventas observadas están conformadas de dos componentes:</p>
<ol style="list-style-type: decimal">
<li>La parte que se explica por la publicidad <span class="math inline">\(\beta_0 + \beta_1 X_i\)</span></li>
<li>El error <span class="math inline">\(e_i\)</span></li>
</ol>
<p>La recta de mejor ajuste se determina encontrando los valores <span class="math inline">\(\beta_0\)</span> y <span class="math inline">\(\beta_1\)</span> que <strong>minimizan</strong> la suma de los <strong>errores cuadráticos</strong> en términos matemáticos <span class="math inline">\(\sum_{i=1}^{n}{e_i^2}\)</span>, este método se lo conoce como <strong>mínimos cuadrados ordinarios</strong>. Intuitivamente la primera idea sería minimizar la suma de los errores <span class="math inline">\(\sum_{i=1}^{n}{e_i}\)</span>, el lector puede verificar que <span class="math inline">\(\sum_{i=1}^{n}{e_i}=0\)</span>.</p>
<p>De la ecuación <a href="lineal.html#eq:regre4">(6.6)</a> se obtiene que</p>
<p><span class="math display" id="eq:regre5">\[\begin{equation}
e_i = Y_i-\beta_0 - \beta_1 X_i
    \tag{6.7}
\end{equation}\]</span></p>
<p>Entonces la suma de los errores cuadráticos equivale a:</p>
<p><span class="math display" id="eq:regre6">\[\begin{equation}
\sum_{i=1}^{n}{e_i^2} = \sum_{i=1}^{n}{\left(Y_i-\beta_0 - \beta_1 X_i\right)^2}
    \tag{6.8}
\end{equation}\]</span></p>
<p>La expresión de la ecuación <a href="lineal.html#eq:regre6">(6.8)</a> se minimiza utilizando derivadas, el resultado obtenido de esa minimización se muestra en las ecuaciones <a href="lineal.html#eq:pendiente">(6.9)</a> y <a href="lineal.html#eq:inter">(6.10)</a></p>
<p><span class="math display" id="eq:pendiente">\[\begin{equation}
\beta_1 = \dfrac{n\sum_{i=1}^{n}{X_iY_i}-\sum_{i=1}^{n}{X_i}\sum_{i=1}^{n}{Y_i}}{n\sum_{i=1}^{n}{X_i^2}-\left(\sum_{i=1}^{n}{X_i}\right)^2}
    \tag{6.9}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:inter">\[\begin{equation}
\beta_0 = \bar{Y}-\beta_1\bar{X}
    \tag{6.10}
\end{equation}\]</span></p>
<div id="regresion-lineal-en-r" class="section level3">
<h3><span class="header-section-number">6.2.1</span> Regresión lineal en R</h3>
<p>Para realizar regresión lineal en R se puede usar la función <code>lm( )</code>, el uso de la función es <code>lm(formula, datos)</code>. En este caso se quiere obtener los coeficientes de la ecuación de regresión</p>
<p><span class="math display" id="eq:modelo0">\[\begin{equation}
  \text{Ventas} = \beta_0 + \beta_1 \text{Publicidad} + \epsilon
    \tag{6.11}
\end{equation}\]</span></p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb122-1" title="1"><span class="kw">set.seed</span>(<span class="fl">1.8</span>)</a>
<a class="sourceLine" id="cb122-2" title="2">Publicidad &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>, <span class="dt">mean=</span><span class="dv">80</span>, <span class="dt">sd=</span><span class="dv">10</span>)</a>
<a class="sourceLine" id="cb122-3" title="3">Ventas &lt;-<span class="st"> </span><span class="dv">30</span> <span class="op">+</span><span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>,<span class="dt">mean=</span><span class="dv">4</span>,<span class="dt">sd=</span><span class="fl">0.3</span>)<span class="op">*</span>Publicidad <span class="op">+</span><span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>,<span class="dt">mean =</span> <span class="dv">0</span>,<span class="dt">sd=</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb122-4" title="4"></a>
<a class="sourceLine" id="cb122-5" title="5">m1 =<span class="st"> </span><span class="kw">lm</span>(Ventas <span class="op">~</span><span class="st"> </span>Publicidad)</a>
<a class="sourceLine" id="cb122-6" title="6"><span class="kw">summary</span>(m1)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Ventas ~ Publicidad)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -43.588 -15.371  -3.649  14.335  59.570 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  34.6898    21.4169    1.62    0.109    
## Publicidad    3.9312     0.2625   14.97   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 23.46 on 98 degrees of freedom
## Multiple R-squared:  0.6959, Adjusted R-squared:  0.6928 
## F-statistic: 224.2 on 1 and 98 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div id="coefregre" class="section level3">
<h3><span class="header-section-number">6.2.2</span> Interpretación de los coeficientes de regresión</h3>
<p>En el apartado <code>Coefficients:</code> del resultado la primera columna corresponde a los valores estimados de los coeficientes. La ecuación de regresión obtenida al reemplazar los coeficientes obtenidos en la ecuación <a href="lineal.html#eq:modelo0">(6.11)</a> seria:</p>
<p><span class="math display" id="eq:modelo">\[\begin{equation}
\text{Ventas} = 34.69 + 3.93\text{Publicidad} + \epsilon 
    \tag{6.12}
\end{equation}\]</span></p>
<p>El primer coeficiente a interpretar es el de la pendiente en este caso <span class="math inline">\(\beta_1\)</span> es igual a 3.93 esto se lo observa en la salida de R en el apartado <code>Coefficients:</code> el valor estimado para la publicidad, de manera general el valor de <span class="math inline">\(\beta_1\)</span> se interpreta como el cambio en la variable dependiente (<span class="math inline">\(Y\)</span>) por cada aumento de <span class="math inline">\(1\)</span> unidad en la variable independiente (<span class="math inline">\(X\)</span>). En este caso por cada aumento de <span class="math inline">\(1\)</span> dólar en la inversión en publicidad, el nivel de ventas sube en promedio 3.93.</p>
<p>Por otro lado <span class="math inline">\(\beta_0\)</span> es igual a 34.69, <span class="math inline">\(\beta_0\)</span> se interpreta como el valor que toma la variable dependiente cuando la variable independiente es igual a <span class="math inline">\(0\)</span>. En este caso cuando la inversión en publicidad es igual a <span class="math inline">\(0\)</span> las ventas son en promedio iguales a 34.69.</p>
</div>
<div id="bondad-de-ajuste-del-modelo-de-regresion" class="section level3">
<h3><span class="header-section-number">6.2.3</span> Bondad de Ajuste del modelo de regresión</h3>
<p>Una vez calculada la recta de regresión quizás nos preguntemos si esta da un buen ajuste a los datos, nos interesa si las observaciones se alejan o se acercan de la recta. Si el ajuste es pobre, quizás el efecto de la variable independiente en la dependiente no es lo suficientemente fuerte. El lector debe fijarse en que, aún cuando no haya efecto de <span class="math inline">\(X\)</span> sobre <span class="math inline">\(Y\)</span> se puede calcular la recta de regresión. Medir la bondad de ajuste de una regresión nos permite discriminar entre un buen y un mal modelo de regresión.</p>
<p>La bondad de ajuste se calcula comparando dos rectas, la recta de regresión y la recta promedio de <span class="math inline">\(Y\)</span> que es una recta horizontal dibujada en el promedio de <span class="math inline">\(Y\)</span>, como se observa en la figura <a href="lineal.html#fig:determinacion">6.11</a> la linea punteada de negro representa el valor promedio de <span class="math inline">\(Y\)</span>, se ilustra además una observación <span class="math inline">\(\left(X_i,Y_i\right)\)</span>. La diferencia entre <span class="math inline">\(Y\)</span> y <span class="math inline">\(\bar{Y}\)</span> está dividida en dos partes la primera parte es la parte que explica la recta de regresión <span class="math inline">\(\hat{Y}-\bar{Y}\)</span>. y la segunda parte es el término de error <span class="math inline">\(Y-\hat{Y}\)</span></p>
<div class="figure" style="text-align: center"><span id="fig:determinacion"></span>
<img src="error5.png" alt="Bondad de Ajuste de un Modelo de Regresión Lineal" width="50%" />
<p class="caption">
Figura 6.11: Bondad de Ajuste de un Modelo de Regresión Lineal
</p>
</div>
<p>Un buen modelo de regresión debería explicar una gran porción de las diferencias entre <span class="math inline">\(Y\)</span> y <span class="math inline">\(\bar{Y}\)</span>, por lo tanto la longitud <span class="math inline">\(\hat{Y}-\bar{Y}\)</span> debería ser más grande respecto a <span class="math inline">\(Y-\bar{Y}\)</span>. Entonces una medida de ajuste puede ser <span class="math inline">\(\frac{\hat{Y}-\bar{Y}}{Y_i-\bar{Y}}\)</span>, esto lo deberíamos usar para todas las observaciones por lo que deberiamos sumar estas expresiones, sin embargo en el caso de <span class="math inline">\(\sum_{i=1}^{n}{Y_i-\bar{Y}}\)</span> esto es igual a <span class="math inline">\(0\)</span>, para saltar este problema usamos el cuadrado de las expresiones para que se hagan positivas. De esta forma definimos:</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(\sum_{i=1}^{n}{\left(Y_i-\bar{Y}\right)^2}\)</span>, conocido como la suma total de cuadrados (STC).</li>
<li><span class="math inline">\(\sum_{i=1}^{n}{\left(Y_i-\hat{Y}\right)^2}\)</span>, suma cuadrática del error (SCE)</li>
</ol>
<p>La bondad de ajuste <span class="math inline">\(R^2\)</span> se define como:</p>
<p><span class="math display" id="eq:rscuared">\[\begin{equation}
R^2 = \dfrac{STC-SCE}{STC} = 1 - \dfrac{SCE}{STC}
    \tag{6.13}
\end{equation}\]</span></p>
<p>El <span class="math inline">\(R^2\)</span> se lo interpreta como la proporción de la variabilidad de <span class="math inline">\(Y\)</span> explicada por <span class="math inline">\(X\)</span>. En el modelo obtenido en la sección <a href="lineal.html#coefregre">6.2.2</a> se obtuvo un <span class="math inline">\(R^2\)</span> de 0.6959 este valor se observa en las últimas líneas del resumen del modelo donde dice <code>Multiple R-squared</code>, se interpreta que el 69.59% de la variabilidad de las ventas son explicadas por la inversión en publicidad.</p>
</div>
<div id="pruebas-de-hipotesis-para-los-coeficientes-de-la-regresion" class="section level3">
<h3><span class="header-section-number">6.2.4</span> Pruebas de Hipótesis para los coeficientes de la regresión</h3>
<p>El resumen de R muestra los valores <em>p</em> para las hipótesis nulas <span class="math inline">\(\beta_0=0\)</span> y <span class="math inline">\(\beta_1=0\)</span>, el criterio que se usa para aceptar o rechazar la hipótesis nula es el criterio que se explica en la sección <a href="ph.html#pvalor">5.2.2</a>.</p>
<p>En este caso se puede ver en el resumen que para el intercepto <span class="math inline">\(\beta_0\)</span> el valor <em>p</em> es <span class="math inline">\(0.109\)</span> y para la pendiente <span class="math inline">\(\beta_1\)</span> el valor <em>p</em> es <span class="math inline">\(&lt;2 \times 10^{-16}\)</span> junto a los valores <em>p</em> hay unos códigos de significancia
lo mejor es simplemnte usar el criterio ya mencionado, en este caso el valor <em>p</em> del intercepto nos indica que no se puede rechazar <span class="math inline">\(H_0: \beta_0=0\)</span> a un nivel de significancia de <span class="math inline">\(0.05\)</span>, mientras que para el caso de la pendiente el valor <em>p</em> nos indica que rechazamos <span class="math inline">\(H_0: \beta_1=0\)</span> a un nivel de significancia de <span class="math inline">\(0.05\)</span>.</p>
<p>Además en la última linea de la salida del resumen del modelo de regresión se obtiene un estadístico <span class="math inline">\(F\)</span> de <span class="math inline">\(224.2\)</span> este estadístico es un buen indicador de si existe una relación entre la variable independiente y dependiente. A mayor distancia del estadístico de <span class="math inline">\(1\)</span> el modelo es mejor. Qué tan grande debe ser el valor depende tanto del número de datos y de variables predictoras. En este caso el estadístico está lejos de <span class="math inline">\(1\)</span>, además el valor <span class="math inline">\(p\)</span> general al final del modelo es para el estadístico <span class="math inline">\(F\)</span> en este caso el valor <span class="math inline">\(p\)</span> de <span class="math inline">\(&lt;2 \times10^{-16}\)</span> nos indica que el modelo global es significativo.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="correl.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="mult.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["EPCA.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
